# Generated by Django 4.0.2 on 2022-02-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transectiondetail',
            name='email',
        ),
        migrations.RemoveField(
            model_name='transectiondetail',
            name='username',
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='image',
            field=models.ImageField(default='Image003.png', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='phoneno',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='totalbalance',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='transectiondetail',
            name='recieveremail',
            field=models.EmailField(default='anonymous@anonymous.com', max_length=30),
        ),
        migrations.AddField(
            model_name='transectiondetail',
            name='recievername',
            field=models.CharField(default='anonymous', max_length=30),
        ),
        migrations.AddField(
            model_name='transectiondetail',
            name='senderemail',
            field=models.EmailField(default='anonymous@anonymous.com', max_length=30),
        ),
        migrations.AddField(
            model_name='transectiondetail',
            name='sendername',
            field=models.CharField(default='anonymous', max_length=30),
        ),
        migrations.AlterField(
            model_name='transectiondetail',
            name='account_balance',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='transectiondetail',
            name='credited_amt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transectiondetail',
            name='deducted_amt',
            field=models.IntegerField(default=0),
        ),
    ]
