# Generated by Django 4.0.2 on 2022-02-10 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0002_remove_transectiondetail_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transectiondetail',
            name='account_balance',
        ),
    ]
