# Generated by Django 4.0.2 on 2022-02-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0002_remove_transectiondetail_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transectiondetail',
            name='account_balance',
        ),
        migrations.AlterField(
            model_name='transectiondetail',
            name='senderemail',
            field=models.EmailField(default='anonymous@gmail.com.com', max_length=30),
        ),
    ]
