# Generated by Django 4.0.1 on 2022-02-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0002_customeraccount_customer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transectiondetail',
            name='email',
        ),
        migrations.RemoveField(
            model_name='transectiondetail',
            name='username',
        ),
        migrations.AddField(
            model_name='transectiondetail',
            name='recieveremail',
            field=models.EmailField(default='anonymous@anonymous.com', max_length=30),
        ),
        migrations.AddField(
            model_name='transectiondetail',
            name='recievername',
            field=models.CharField(default='anonymous', max_length=30),
        ),
        migrations.AddField(
            model_name='transectiondetail',
            name='senderemail',
            field=models.EmailField(default='anonymous@anonymous.com', max_length=30),
        ),
        migrations.AddField(
            model_name='transectiondetail',
            name='sendername',
            field=models.CharField(default='anonymous', max_length=30),
        ),
    ]
