# Generated by Django 4.0.2 on 2022-02-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0003_remove_transectiondetail_account_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transectiondetail',
            old_name='credited_amt',
            new_name='money_amt',
        ),
        migrations.RemoveField(
            model_name='transectiondetail',
            name='deducted_amt',
        ),
        migrations.AlterField(
            model_name='transectiondetail',
            name='recieveremail',
            field=models.EmailField(default='anonymous@gmail.com', max_length=30),
        ),
        migrations.AlterField(
            model_name='transectiondetail',
            name='senderemail',
            field=models.EmailField(default='anonymous@gmail.com', max_length=30),
        ),
    ]
