# Generated by Django 4.0.1 on 2022-02-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0003_remove_transectiondetail_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='customer_image',
            field=models.ImageField(default='', upload_to='Bank/images'),
        ),
    ]
