# Generated by Django 4.0.1 on 2022-02-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0004_alter_customeraccount_customer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='customer_image',
            field=models.ImageField(default='', upload_to='media/Bank/images'),
        ),
    ]
