# Generated by Django 4.0.1 on 2022-02-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0006_remove_customeraccount_customer_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='image',
            field=models.ImageField(default='', upload_to='Bank/images/'),
        ),
    ]
