# Generated by Django 4.0.2 on 2022-02-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0007_alter_customeraccount_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccount',
            name='totalbalance',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='image',
            field=models.ImageField(default='Bank/images', upload_to='media/'),
        ),
    ]
