# Generated by Django 4.0.2 on 2022-02-08 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0008_customeraccount_totalbalance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='image',
            field=models.ImageField(default='static/media/Image003.png', upload_to='media/'),
        ),
    ]
