# Generated by Django 4.0.2 on 2022-02-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0010_alter_customeraccount_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccount',
            name='phoneno',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
