# Generated by Django 4.0.2 on 2022-02-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0011_customeraccount_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transectiondetail',
            name='account_balance',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='transectiondetail',
            name='credited_amt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transectiondetail',
            name='deducted_amt',
            field=models.IntegerField(default=0),
        ),
    ]
